In [1]:
import pandas as pd

In [2]:
npr=pd.read_csv('npr.csv')

In [3]:
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [4]:
npr['Article'][1]

'  Donald Trump has used Twitter  —   his preferred means of communication  —   to weigh in on a swath of foreign policy issues over the past few weeks. His comments give a glimpse into how his incoming administration will deal with pressing foreign matters  —   but also highlight how reactionary comments on social media can immediately spur international concern and attention. And his staff has indicated that taking to Twitter to air his concerns or, often, grievances, won’t end once he enters the Oval Office. On Wednesday, Trump blasted the U. S.’s abstention from the U. N. Security Council vote on Israeli settlements earlier this month. The tweets came just hours before Secretary of State John Kerry gave a speech defending the decision and calling the continued building of settlements on Palestinian territory in the West Bank a threat to the   solution in the region. Trump’s support for Israel and Prime Minister Benjamin Netanyahu  —   who has had a fraught relationship with Preside

In [5]:
from sklearn.feature_extraction.text import CountVectorizer

In [6]:
cv=CountVectorizer(max_df=0.95,min_df=2,stop_words='english')

In [7]:
dtm=cv.fit_transform(npr['Article'])

In [8]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [9]:
from sklearn.decomposition import LatentDirichletAllocation

In [10]:
LDA=LatentDirichletAllocation(n_components=7,random_state=42)

In [11]:
LDA.fit(dtm)

C:\Users\Satish\Anaconda3\lib\site-packages\sklearn\decomposition\online_lda.py:536: DeprecationWarning: The default value for 'learning_method' will be changed from 'online' to 'batch' in the release 0.20. This warning was introduced in 0.18.
  DeprecationWarning)


LatentDirichletAllocation(batch_size=128, doc_topic_prior=None,
             evaluate_every=-1, learning_decay=0.7, learning_method=None,
             learning_offset=10.0, max_doc_update_iter=100, max_iter=10,
             mean_change_tol=0.001, n_components=7, n_jobs=1,
             n_topics=None, perp_tol=0.1, random_state=42,
             topic_word_prior=None, total_samples=1000000.0, verbose=0)

In [13]:
len(cv.get_feature_names())

54777

In [14]:
type(cv.get_feature_names())

list

In [15]:
cv.get_feature_names()[50000]

'transcribe'

In [16]:
import random

random_word_id=random.randint(0,54777)

cv.get_feature_names()[random_word_id]

'extraordinaire'

In [17]:
#Grab the topics

In [18]:
len(LDA.components_)

7

In [19]:
type(LDA.components_)

numpy.ndarray

In [20]:
LDA.components_.shape

(7, 54777)

In [21]:
LDA.components_

array([[2.55030234e+01, 1.18160521e+03, 1.42857161e-01, ...,
        1.42942888e-01, 1.42865635e-01, 1.42994709e-01],
       [1.75938770e+01, 7.79163845e+00, 1.42871959e-01, ...,
        1.42857152e-01, 1.43057304e-01, 1.42990129e-01],
       [5.56830532e+00, 7.61579261e+02, 1.42857370e-01, ...,
        4.84616992e+00, 2.46543716e+00, 1.42942152e-01],
       ...,
       [1.43329722e-01, 6.12135291e+02, 1.42857193e-01, ...,
        1.42868589e-01, 1.42859011e-01, 1.42897792e-01],
       [3.89096469e+01, 1.97272208e+01, 4.00585507e+00, ...,
        1.43174190e-01, 1.45396934e-01, 2.17293923e+00],
       [5.82136826e+00, 1.76095158e+03, 1.43163938e-01, ...,
        1.42994603e-01, 1.43326983e-01, 1.42965349e-01]])

In [22]:
single_topic=LDA.components_[0]

In [23]:
single_topic.argsort()[-10:]

array([ 9511, 49613, 53019, 11657, 21228, 40955, 36283, 37374, 42993,
       42561], dtype=int64)

In [27]:
top_ten_words=single_topic.argsort()[-10:]

In [29]:
for index in top_ten_words:
    print(cv.get_feature_names()[index])

city
told
war
country
government
reports
people
police
says
said


In [31]:
for i,topic in enumerate(LDA.components_):
    print(f"The top 15 words for topic #{i}")
    print([cv.get_feature_names()[index] for index in topic.argsort()[-15:]])
    print('\n')

The top 15 words for topic #0
['state', 'attack', 'killed', 'according', 'military', 'city', 'told', 'war', 'country', 'government', 'reports', 'people', 'police', 'says', 'said']


The top 15 words for topic #1
['russian', 'npr', 'fbi', 'did', 'clinton', 'told', 'media', 'white', 'campaign', 'russia', 'house', 'news', 'president', 'said', 'trump']


The top 15 words for topic #2
['world', 'year', 'make', 'day', 'home', 'time', 'city', 'new', 'years', 'just', 'people', 'water', 'like', 'food', 'says']


The top 15 words for topic #3
['women', 'don', 'just', 'research', 'like', 'university', 'children', 'percent', 'care', 'study', 'students', 'school', 'health', 'people', 'says']


The top 15 words for topic #4
['vote', 'court', 'new', 'percent', 'republican', 'law', 'campaign', 'obama', 'states', 'people', 'president', 'clinton', 'state', 'said', 'trump']


The top 15 words for topic #5
['ve', 'going', 'years', 'don', 'life', 'new', 'really', 'way', 'says', 'know', 'think', 'time', 'pe

In [32]:
topic_results=LDA.transform(dtm)

In [36]:
topic_results[0].round(2)

array([0.07, 0.68, 0.01, 0.  , 0.22, 0.  , 0.02])