In [1]:
import sys
sys.version

'3.6.6 | packaged by conda-forge | (default, Jul 26 2018, 11:48:23) [MSC v.1900 64 bit (AMD64)]'

In [29]:
import os
from pathlib import Path

CHART_DIR=Path("chart")
if not CHART_DIR.exists():
    CHART_DIR.mkdir()
    
DATA_DIR=Path("data")
if not DATA_DIR.exists():
    raise Exception("Data directory %s not found"  % CHART_DIR.absolute())

In [30]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy
DPI=300
%matplotlib inline

In [31]:
#Converting raw text into a bag of words

In [32]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer= CountVectorizer(min_df=1)
print(vectorizer)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)


In [33]:
content=["How to format my hard disk", 
        " Hard disk format  problems "]
X=vectorizer.fit_transform(content)
vectorizer.get_feature_names()

['disk', 'format', 'hard', 'how', 'my', 'problems', 'to']

In [34]:
print(X.toarray())

[[1 1 1 1 1 0 1]
 [1 1 1 0 0 1 0]]


In [35]:
print(X.toarray().transpose())

[[1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [0 1]
 [1 0]]


In [36]:
#Counting words

In [42]:
TOY_DIR =DATA_DIR / "toy"
posts=[p.read_text() for p in TOY_DIR.iterdir()]
from sklearn.feature_extraction.text import CountVectorizer
vectorizer=CountVectorizer(min_df=1)

In [45]:
X_train=vectorizer.fit_transform(posts)
num_samples,num_features=X_train.shape
print("#sample: %d,#feature:%d" %(num_samples,num_features))

#sample: 5,#feature:25


In [46]:
print(vectorizer.get_feature_names())

['about', 'actually', 'capabilities', 'contains', 'data', 'databases', 'images', 'imaging', 'interesting', 'is', 'it', 'learning', 'machine', 'most', 'much', 'not', 'permanently', 'post', 'provide', 'save', 'storage', 'store', 'stuff', 'this', 'toy']


In [48]:
new_post="imaging databases"
new_post_vec=vectorizer.transform([new_post])
print(new_post_vec)

  (0, 5)	1
  (0, 7)	1


In [49]:
print(new_post_vec.toarray())

[[0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [50]:
def dist_raw(v1,v2):
    delta=v1-v2
    return scipy.linalg.norm(delta.toarray())

In [ ]:
def best_post(X,new_vec,dist_func):
    best_doc=None
    best_dist=float('inf')
    best_i=None
    for i, post in enumerate(posts):
        if post == new_post:
            continue 
        post_vec=X.getrows(i)
        d=dist_func(post_vec,new_vec)
        print("==Post %i with dist=%.2f '%s'" %(i,d,post))
        if d < best_dist:
            best_dist=d
            best_i=i
    print("\n==> Best post is %i with dist=%.2f" %(best_i,best_dist))

best_post(X_train,new_post_vec,dist_raw)